### ISSUE TITLE
how to solve "File is not a zip file"

### ISSUE THREAD

**Issue by randomssr** [waugustus/CarpetFuzz#17]
Hello, when I reproducing this work using docker and run the “Minimal Working example”, and I met this problem.  Could you tell me the reason for this problem?
sudo docker pull 4ugustus/carpetfuzz 
```
/usr/local/lib/python3.8/dist-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
Your label namespace was 'pos'. We recommend you use a namespace ending with 'labels' or 'tags', so we don't add UNK and PAD tokens by default to your vocabulary.  See documentation for `non_padded_namespaces` parameter in Vocabulary.
Traceback (most recent call last):
  File "/root/CarpetFuzz/scripts/find_relationship.py", line 108, in <module>
    implicit_rsent_list = identifyImplicitRSentences(program, opt_desc_dict)
  File "/root/CarpetFuzz/scripts/find_relationship.py", line 43, in identifyImplicitRSentences
    topic_sent_list = nlp_util.extractTopicSentList(program, opt_desc_dict)
  File "/root/CarpetFuzz/scripts/utils/nlp_util.py", line 178, in extractTopicSentList
    predicate, object, prt = self.__getPredAndObj(topic_sentence)
  File "/root/CarpetFuzz/scripts/utils/nlp_util.py", line 700, in __getPredAndObj
    prt = find_prep_result[0] if len(wordnet.synsets("%s_%s" % (predicate, find_prep_result[0]))) > 0 else ""
  File "/usr/local/lib/python3.8/dist-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/usr/local/lib/python3.8/dist-packages/nltk/corpus/util.py", line 89, in __load
    corpus = self.__reader_cls(root, *self.__args, **self.__kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nltk/corpus/reader/wordnet.py", line 1176, in __init__
    self.provenances = self.omw_prov()
  File "/usr/local/lib/python3.8/dist-packages/nltk/corpus/reader/wordnet.py", line 1285, in omw_prov
    fileids = self._omw_reader.fileids()
  File "/usr/local/lib/python3.8/dist-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/usr/local/lib/python3.8/dist-packages/nltk/corpus/util.py", line 81, in __load
    root = nltk.data.find(f"{self.subdir}/{self.__name}")
  File "/usr/local/lib/python3.8/dist-packages/nltk/data.py", line 555, in find
    return find(modified_name, paths)
  File "/usr/local/lib/python3.8/dist-packages/nltk/data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "/usr/local/lib/python3.8/dist-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nltk/data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/usr/local/lib/python3.8/dist-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nltk/data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by waugustus** [comment]
Hi, this issue is due to the missing essential files for NLTK in the precompiled Docker image. I will update the image to address this in the future. To temporarily resolve this problem, you can run the following command inside the container:

```
echo -e "import nltk\nnltk.download('averaged_perceptron_tagger')\nnltk.download('omw-1.4')\nnltk.download('punkt')\nnltk.download('wordnet')" | python3
```

This will download the necessary NLTK resources.

**Comment by waugustus** [comment]
Fixed in https://hub.docker.com/layers/4ugustus/carpetfuzz/latest/images/sha256-88eca17299fc4609118176bfb7759a1a0e1f28acc0efa27213f1ebb51bf5f65f

**Comment by randomssr** [comment]
Got it! Thank you!
